### ISSUE TITLE
Perspective reversed

### ISSUE THREAD

**Issue by josephfh** [levskaya/polyhedronisme#1]
Great project. I've noticed that the persp_ratio is slightly reversed. You can see this most clearly by viewing a cube.

Setting persp_ratio to 1.2 instead of .8 seems to fix this.

**Comment by levskaya** [comment]
Woops!  Thanks for catching that, don't know how I missed it.  I patched the live version, but I need to fix up my local repo's branches before pushing the change neatly to the master branch here.
