### ISSUE TITLE
MANY incorrect results

### ISSUE THREAD

**Issue by GlassGhost** [levskaya/polyhedronisme#10]
jC - https://en.wikipedia.org/wiki/Rhombic_dodecahedron  
jD - https://en.wikipedia.org/wiki/Rhombic_triacontahedron  
ccD, cccD, ctkD, cdktI, ctkD, wD - https://en.wikipedia.org/wiki/Goldberg_polyhedron tkt5daD, tdtdtkD, dktI work and are beautiful

**Comment by LeoStaley** [comment]
If you prefix jC and jD like this: C300jC and C300jD, you'll get correct results. for some reason, it doesn't automatically create the cannonical versions, and you have to add that operator to make the cannonical versions.

**Comment by levskaya** [comment]
Sorry to vanish from comments for several years.  I designed this to give end-users maximum freedom to either canonicalize the shape or not - for some ops not canonicalizing can yield beautiful shapes as well.
