### ISSUE TITLE
Specify chirality of snub, whirl, propellor, and gyro operators

### ISSUE THREAD

**Issue by LeoStaley** [levskaya/polyhedronisme#11]
Please add the ability to specify the chirality of the rotational operations, snub, whirl, propellor, and gyro. If you use one chirality of one of those operators, and use another chirality on another operator after it, the resulting shape is much different.

**Comment by levskaya** [comment]
Have you tried using the reflect operator 'r' after one of these chiral ops to change its chirality?  Let me know if you're looking for something more.
