### ISSUE TITLE
How are colors chosen for the faces?

### ISSUE THREAD

**Issue by pantsmann** [levskaya/polyhedronisme#12]
Or in other words, do the colors indicate anything?

**Comment by Pr0methean** [comment]
Faces of the same color are supposed to all be congruent, as I understand it.

**Comment by levskaya** [comment]
Notionally it's congruence.  Yeah this sucks hard at the moment, it's tricky to make a good congruence heuristic that doesn't break on numerical error but that doesn't accidentally identify non-congruent pairs as being the same.  The hack I have could be much better.

**Comment by levskaya** [comment]
So I finally had time to figure out the 5 different ways I was screwing up the congruence signatures used to color the faces.  I must have been super tired when I wrote that code years ago.  Anyway, it's all fixed up so now the congruent faces get the same colors and everything looks a thousand times better.

**Comment by pantsmann** [comment]
Thanks. It does look better.
