### ISSUE TITLE
Incorrect coloring for C1000jpC

### ISSUE THREAD

**Issue by Pr0methean** [levskaya/polyhedronisme#13]
In C1000jpC, one kite-shaped face at each of the degree-3 vertices is the same color as the square faces.

**Comment by Pr0methean** [comment]
Interestingly, this doesn't happen with C10000jjpC, in which all the kite-shaped faces are the same color and the square faces are not that color.

**Comment by levskaya** [comment]
This is part of a known problem with the congruent-faces coloring heuristic... it's set to be a bit permissive right now.  I'll try to invent a better heuristic one of these years.
