### ISSUE TITLE
meta equivalent to k3j?

### ISSUE THREAD

**Issue by andybak** [levskaya/polyhedronisme#14]
Swapping m for k3j doesn't produce the same topology.

Also https://github.com/elfnor/conway_polyhedron_operators seems to think that meta should be "ambo dual kis" (or "kda" if you treat the operators like function calls rather than a chain)

**Comment by imagirom** [comment]
The reason is that it is not k3j but k4j:
m = k4j = kj (j only produces faces with 4 corners) = kda
