### ISSUE TITLE
download failed - network error (output too big?)

### ISSUE THREAD

**Issue by NNNenov** [levskaya/polyhedronisme#15]
Hello, 
I was just about to say that there's an issue downloading larger objects, but I think its a browser issue, I tried using Firefox and the download worked fine, seems to be a problem with Chrome.

I'm having so much fun playing around with this, thank you.

**Comment by levskaya** [comment]
Glad you liked it - Sorry to take so long to respond.  I've tried reproducing the issue on current chrome but even giant models seem to work fine now.

**Comment by welcroft** [comment]
I've been trying to download project of 2,4Gb and it stops at last to 824Mb if not before. Tried it on 3 different browsers so far with no difference. some limit on size?

**Comment by levskaya** [comment]
Yeah most browsers set a safety limit for the Blob / Filesaver APIs.  There's not a quick fix for this.  We'd have to rewrite the code to use https://github.com/jimmywarting/StreamSaver.js or wait until https://wicg.github.io/file-system-access/ is supported by browsers.
