### ISSUE TITLE
Optimize for similar shapes

### ISSUE THREAD

**Issue by pjaytycy** [levskaya/polyhedronisme#18]
The current A and C operators focus on creating flat regular faces. For some recipes, there are only minor differences in the "different" faces. Depending on how often you apply A or C operators, you can get varying results in the amount of different faces.

For real construction it's sometimes more important to reduce the amount of different faces instead of making the faces regular or the polygon spherical. Do you have any ideas on how to implement an operator that focuses on this aspect?

**Comment by levskaya** [comment]
For small refinements one could cluster the faces in a few different ways and try to find the best congruence per-cluster for applying a gradient on the nodes... but there are many shapes where convergence might not be guaranteed (different face classes pull nodes in different incompatible directions) given the symmetry constraints of a given 3D solid.  It's a neat idea to explore -  I'm afraid I wouldn't myself have the time to implement such a thing.
