### ISSUE TITLE
Dual operator fails on many johnson solids

### ISSUE THREAD

**Issue by LeoStaley** [levskaya/polyhedronisme#19]
When using the dual operator on many johnson solids, polyhedronise me produces a non-convex polyhedron when it should produce a convex polyhedron. For example, dJ3, dJ27, dJ34, dJ37 (and many more) produce non-convex polyhedra instead of the correct polyhedra. 

For example, the dual of J37 should be the [Pseudo deltoidal icositetrahedron](https://en.wikipedia.org/wiki/Pseudo-deltoidal_icositetrahedron), and J27 should be the [Trapezo-rhombic dodecahedron](https://en.wikipedia.org/wiki/Trapezo-rhombic_dodecahedron).

These are all convex, but polyhedroniseme produces non-convex results.

**Comment by levskaya** [comment]
@LeoStaley - sorry for the exceptionally long time to reply.  polyhedronisme doesn't automatically "canonicalize" geometry, but it does have a canonicalization/refinement operator "C" that takes a number-of-iterations parameter.  So, if you instead try "C1000J37" and "C1000J27" you should get geometry very close to the ideal form.
