### ISSUE TITLE
Number of faces count

### ISSUE THREAD

**Issue by Andrey5045** [levskaya/polyhedronisme#22]
I have played with coordinates which I fished out from this model's obj file:
https://levskaya.github.io/polyhedronisme/?recipe=A100wrwwdkD
(10292 faces)
and put them into 3D world of Roblox.
When I cycle through lines of points which define faces I see this:
![image](https://github.com/levskaya/polyhedronisme/assets/44962284/6f73a2d6-30a8-4009-9beb-cda7fa44ca71)
Let's look at it from the inside
![image](https://github.com/levskaya/polyhedronisme/assets/44962284/0c2db9c9-f3f4-45ea-9246-2fe6a6297145)

As you can see, not all the entire surface is covered and all the faces do define a correct pattern... and they are 10292 faces.
Not all the dots (which are 20580 vertices) are connected. So to say, it is 10292 faces in the obj file which is enough to create your model, but the "physical" figure itself has more faces... 10292 times 6?

**Comment by ToddTempleman** [comment]
Very cool. Thanks so much for your time and effort on this. I’ll look for a different way to get the object I need, but this was informative and will save me work in the future. Much appreciated!On May 23, 2023, at 5:45 AM, Andrey5045 ***@***.***> wrote:﻿
I have played with coordinates which I fished out from this model's obj file:
https://levskaya.github.io/polyhedronisme/?recipe=A100wrwwdkD
(10292 faces)
and put them into 3D world of Roblox.
When I cycle through lines of points which define faces I see this:

Let's look at it from the inside

As you can see, not all the entire surface is covered and all the faces do define a correct pattern... and they are 10292 faces.
Not all the dots (which are 20580 vertices) are connected. So to say, it is 10292 faces in the obj file which is enough to create your model, but the "physical" figure itself has more faces... 10292 times 6?

**Comment by Andrey5045** [comment]
Ha-ha!! May bad! I am sorry for a stupid error I made and raising the issue; now I found a bug in my code. It drew only the first line  of the figure ... not all the 6 or 5. It was enough to create a correct pattern but did not cover the entire surface.
![image](https://github.com/levskaya/polyhedronisme/assets/44962284/ccf0cd32-2cec-4a6c-aaa8-c23960adc852)
