### ISSUE TITLE
Quinto operator (q)

### ISSUE THREAD

**Issue by AlexPoulsen** [levskaya/polyhedronisme#9]
[https://en.wikipedia.org/wiki/Conway_polyhedron_notation#Extended_operators](https://en.wikipedia.org/wiki/Conway_polyhedron_notation#Extended_operators)

I was looking on wikipedia and saw this additional operator

**Comment by AlexPoulsen** [comment]
also, if you are going to add q, etc, mod, atgj, and aob are a fairly cool set of operators and totally deserve a letter

**Comment by levskaya** [comment]
quinto 'q' operator is finally added, thanks for waiting 2.5 years ;)
